---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    {{- include "golanglab5.labels" . | nindent 4 }}
data:
  config.k8s.yaml: |
{{- required "set config.configK8sContent via --set-file config.configK8sContent=config/config.k8s.yaml" .Values.config.configK8sContent | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.mysqlInitSql }}
  labels:
    {{- include "golanglab5.labels" . | nindent 4 }}
data:
  init.sql: |
{{- required "set config.mysqlInitSqlContent via --set-file config.mysqlInitSqlContent=config/sql/init.sql" .Values.config.mysqlInitSqlContent | nindent 4 }}
