// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/nnieie/golanglab5/cmd/api/biz/handler"
	"github.com/nnieie/golanglab5/cmd/api/biz/handler/api"
	"github.com/nnieie/golanglab5/cmd/api/biz/handler/mw/jwt"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.POST("/user/token/refresh", jwt.RefreshTokenJwtMiddleware.MiddlewareFunc(), api.RefreshToken)
}
