// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/nnieie/golanglab5/cmd/api/biz/handler/mw/jwt"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _mfabindMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _getcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfanslistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendsMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _getfriendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _getlikelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideostreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublishvideolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpopularvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _searchvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishcommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}
