CREATE DATABASE IF NOT EXISTS rpc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rpc;
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(512) DEFAULT NULL,
  `totp` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` DATETIME(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_user_name` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;