// Code generated by Kitex v0.15.1. DO NOT EDIT.

package socialservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	social "github.com/nnieie/golanglab5/kitex_gen/social"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowAction(ctx context.Context, req *social.FollowActionRequest, callOptions ...callopt.Option) (r *social.FollowActionResponse, err error)
	QueryFollowList(ctx context.Context, req *social.QueryFollowListRequest, callOptions ...callopt.Option) (r *social.QueryFollowListResponse, err error)
	QueryFollowerList(ctx context.Context, req *social.QueryFollowerListRequest, callOptions ...callopt.Option) (r *social.QueryFollowerListResponse, err error)
	QueryFriendList(ctx context.Context, req *social.QueryFriendListRequest, callOptions ...callopt.Option) (r *social.QueryFriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) FollowAction(ctx context.Context, req *social.FollowActionRequest, callOptions ...callopt.Option) (r *social.FollowActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowAction(ctx, req)
}

func (p *kSocialServiceClient) QueryFollowList(ctx context.Context, req *social.QueryFollowListRequest, callOptions ...callopt.Option) (r *social.QueryFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFollowList(ctx, req)
}

func (p *kSocialServiceClient) QueryFollowerList(ctx context.Context, req *social.QueryFollowerListRequest, callOptions ...callopt.Option) (r *social.QueryFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFollowerList(ctx, req)
}

func (p *kSocialServiceClient) QueryFriendList(ctx context.Context, req *social.QueryFriendListRequest, callOptions ...callopt.Option) (r *social.QueryFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFriendList(ctx, req)
}
