// Code generated by hertz generator.

package api

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"path/filepath"
	"strings"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/nnieie/golanglab5/internal/api/biz/handler/mw/jwt"
	api "github.com/nnieie/golanglab5/internal/api/biz/model/api"
	"github.com/nnieie/golanglab5/internal/api/pack"
	"github.com/nnieie/golanglab5/internal/api/rpc"
	"github.com/nnieie/golanglab5/kitex_gen/video"
	"github.com/nnieie/golanglab5/pkg/constants"
	"github.com/nnieie/golanglab5/pkg/errno"
	"github.com/nnieie/golanglab5/pkg/logger"
	"github.com/nnieie/golanglab5/pkg/oss"
	"github.com/nnieie/golanglab5/pkg/utils"
)

const sniffLen = 512

var (
	videoBucket     *oss.VideoOSSCli
	videoBucketOnce sync.Once
	videoBucketErr  error
)

func getVideoBucket() (*oss.VideoOSSCli, error) {
	videoBucketOnce.Do(func() {
		snowflake, err := utils.NewSnowflake(9)
		if err != nil {
			videoBucketErr = err
			return
		}

		videoBucket = oss.NewVideoOSSCli(constants.VideoBucketName, constants.VideoPublicDomain, snowflake)
	})

	if videoBucketErr != nil {
		return nil, videoBucketErr
	}

	return videoBucket, nil
}

// PublishVideo .
// @router /video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PublishResponse)

	UserID, err := jwt.ExtractUserID(c)
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}

	// 获取上传的文件
	file, err := c.FormFile("data")
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	if file.Size <= 0 {
		pack.SendErrResp(c, errno.ParamErr.WithMessage("video file is empty"))
		return
	}
	if file.Size > constants.MaxVideoSize {
		pack.SendErrResp(c, errno.FileTooLargeErr.WithMessage("video file exceeds upload limit"))
		return
	}

	openedFile, err := file.Open()
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	defer openedFile.Close()

	header := make([]byte, sniffLen)
	n, err := io.ReadFull(openedFile, header)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		pack.SendErrResp(c, err)
		return
	}
	contentType := http.DetectContentType(header[:n])
	if contentType != "video/mp4" && contentType != "video/x-msvideo" && contentType != "video/x-ms-wmv" &&
		contentType != "video/x-flv" && contentType != "video/quicktime" {
		pack.SendErrResp(c, errno.InvalidFileTypeErr)
		return
	}

	uploadReader := io.MultiReader(bytes.NewReader(header[:n]), openedFile)

	bucket, err := getVideoBucket()
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}

	videoName, err := bucket.GenerateVideoName()
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}

	fileName := strings.TrimSpace(filepath.Base(file.Filename))
	if fileName == "" || fileName == "." {
		fileName = "video"
	}
	videoName = strings.Join([]string{videoName, fileName}, "_")

	fileURL, err := bucket.UploadVideo(videoName, uploadReader, file.Size)
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}

	rpcResp, err := rpc.PublishVideo(ctx, &video.PublishRequest{
		UserId:      UserID,
		VideoUrl:    fileURL,
		FileName:    fileName,
		Title:       req.Title,
		Description: req.Description,
	})

	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	resp.Base = pack.BaseRespRPCToBaseResp(rpcResp.Base)
	if resp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetPublishVideoList .
// @router /video/list [GET]
func GetPublishVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetPublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetPublishListResponse)

	rpcResp, err := rpc.GetPublishList(ctx, &video.GetPublishListRequest{
		UserId:   req.UserID,
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
	})
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	resp.Base = pack.BaseRespRPCToBaseResp(rpcResp.Base)
	if resp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Data = &api.GetPublishListData{
		Items: pack.VideosRPCToVideos(nil),
	}
	if rpcResp.Data != nil {
		resp.Data.Items = pack.VideosRPCToVideos(rpcResp.Data.Items)
		resp.Data.Total = rpcResp.Data.Total
	}

	c.JSON(consts.StatusOK, resp)
}

// GetPopularVideo .
// @router /video/popular [GET]
func GetPopularVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetPopularListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetPopularListResponse)

	rpcResp, err := rpc.GetPopularVideo(ctx, &video.GetPopularVideoListRequest{
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
	})
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	resp.Base = pack.BaseRespRPCToBaseResp(rpcResp.Base)
	if resp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Data = &api.GetPopularListData{
		Items: pack.VideosRPCToVideos(nil),
	}
	if rpcResp.Data != nil {
		resp.Data.Items = pack.VideosRPCToVideos(rpcResp.Data.Items)
	}

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router /video/search [POST]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	logger.Debugf("API SearchVideo req: %+v, keywords: %v", req, req.Keywords)

	resp := new(api.SearchVideoResponse)

	rpcResp, err := rpc.SearchVideo(ctx, &video.SearchVideoRequest{
		Keywords: req.Keywords,
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
		FromDate: req.FromDate,
		ToDate:   req.ToDate,
		Username: req.Username,
	})
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	resp.Base = pack.BaseRespRPCToBaseResp(rpcResp.Base)
	if resp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Data = &api.SearchVideoData{
		Items: pack.VideosRPCToVideos(nil),
	}
	if rpcResp.Data != nil {
		resp.Data.Items = pack.VideosRPCToVideos(rpcResp.Data.Items)
		resp.Data.Total = rpcResp.Data.Total
	}

	c.JSON(consts.StatusOK, resp)
}

// GetVideoStream .
// @router /video/feed [GET]
func GetVideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoStreamRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VideoStreamResponse)

	rpcResp, err := rpc.GetVideoStream(ctx, &video.VideoStreamRequest{
		LatestTime: req.LatestTime,
	})
	if err != nil {
		pack.SendErrResp(c, err)
		return
	}
	resp.Base = pack.BaseRespRPCToBaseResp(rpcResp.Base)
	if resp.Base.Code != errno.SuccessCode {
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Data = &api.VideoStreamData{
		Items: pack.VideosRPCToVideos(nil),
	}
	if rpcResp.Data != nil {
		resp.Data.Items = pack.VideosRPCToVideos(rpcResp.Data.Items)
	}

	c.JSON(consts.StatusOK, resp)
}
