// Code generated by Kitex v0.15.1. DO NOT EDIT.

package interactionservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	interaction "github.com/nnieie/golanglab5/kitex_gen/interaction"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	LikeAction(ctx context.Context, req *interaction.LikeActionRequest, callOptions ...callopt.Option) (r *interaction.LikeActionResponse, err error)
	GetLikeList(ctx context.Context, req *interaction.GetLikeListRequest, callOptions ...callopt.Option) (r *interaction.GetLikeListResponse, err error)
	CommentAction(ctx context.Context, req *interaction.CommentRequest, callOptions ...callopt.Option) (r *interaction.CommentResponse, err error)
	GetCommentList(ctx context.Context, req *interaction.GetCommentListRequest, callOptions ...callopt.Option) (r *interaction.GetCommentListResponse, err error)
	DeleteComment(ctx context.Context, req *interaction.DeleteCommentRequest, callOptions ...callopt.Option) (r *interaction.DeleteCommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractionServiceClient struct {
	*kClient
}

func (p *kInteractionServiceClient) LikeAction(ctx context.Context, req *interaction.LikeActionRequest, callOptions ...callopt.Option) (r *interaction.LikeActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeAction(ctx, req)
}

func (p *kInteractionServiceClient) GetLikeList(ctx context.Context, req *interaction.GetLikeListRequest, callOptions ...callopt.Option) (r *interaction.GetLikeListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLikeList(ctx, req)
}

func (p *kInteractionServiceClient) CommentAction(ctx context.Context, req *interaction.CommentRequest, callOptions ...callopt.Option) (r *interaction.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, req)
}

func (p *kInteractionServiceClient) GetCommentList(ctx context.Context, req *interaction.GetCommentListRequest, callOptions ...callopt.Option) (r *interaction.GetCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, req)
}

func (p *kInteractionServiceClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentRequest, callOptions ...callopt.Option) (r *interaction.DeleteCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}
