// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/nnieie/golanglab5/cmd/api/biz/model/api"
)

// FollowAction .
// @router /relation/action [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FollowActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFollowList .
// @router /following/list [GET]
func GetFollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetFollowListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetFollowListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFansList .
// @router /follower/list [GET]
func GetFansList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetFansListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetFansListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFriendList .
// @router /friends/list [GET]
func GetFriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetFriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetFriendListResponse)

	c.JSON(consts.StatusOK, resp)
}
