// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"github.com/nnieie/golanglab5/kitex_gen/base"
)

type RegisterRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterRequest) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "username",
	2: "password",
}

type RegisterResponse struct {
	Base   *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	UserId *int64         `thrift:"user_id,2,optional" frugal:"2,optional,i64" json:"user_id,omitempty"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

var RegisterResponse_Base_DEFAULT *base.BaseResp

func (p *RegisterResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return RegisterResponse_Base_DEFAULT
	}
	return p.Base
}

var RegisterResponse_UserId_DEFAULT int64

func (p *RegisterResponse) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return RegisterResponse_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *RegisterResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *RegisterResponse) SetUserId(val *int64) {
	p.UserId = val
}

func (p *RegisterResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterResponse) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "base",
	2: "user_id",
}

type LoginRequest struct {
	Username string  `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string  `thrift:"password,2" frugal:"2,default,string" json:"password"`
	MFAcode  *string `thrift:"MFAcode,3,optional" frugal:"3,optional,string" json:"MFAcode,omitempty"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}

var LoginRequest_MFAcode_DEFAULT string

func (p *LoginRequest) GetMFAcode() (v string) {
	if !p.IsSetMFAcode() {
		return LoginRequest_MFAcode_DEFAULT
	}
	return *p.MFAcode
}
func (p *LoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}
func (p *LoginRequest) SetMFAcode(val *string) {
	p.MFAcode = val
}

func (p *LoginRequest) IsSetMFAcode() bool {
	return p.MFAcode != nil
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "username",
	2: "password",
	3: "MFAcode",
}

type LoginResponse struct {
	Base *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	Data *base.User     `thrift:"data,2,optional" frugal:"2,optional,base.User" json:"data,omitempty"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_Base_DEFAULT *base.BaseResp

func (p *LoginResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return LoginResponse_Base_DEFAULT
	}
	return p.Base
}

var LoginResponse_Data_DEFAULT *base.User

func (p *LoginResponse) GetData() (v *base.User) {
	if !p.IsSetData() {
		return LoginResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *LoginResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *LoginResponse) SetData(val *base.User) {
	p.Data = val
}

func (p *LoginResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "base",
	2: "data",
}

type UserInfoRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewUserInfoRequest() *UserInfoRequest {
	return &UserInfoRequest{}
}

func (p *UserInfoRequest) InitDefault() {
}

func (p *UserInfoRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *UserInfoRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *UserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoRequest(%+v)", *p)
}

var fieldIDToName_UserInfoRequest = map[int16]string{
	1: "user_id",
}

type UserInfoResponse struct {
	Base *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	Data *base.User     `thrift:"data,2,optional" frugal:"2,optional,base.User" json:"data,omitempty"`
}

func NewUserInfoResponse() *UserInfoResponse {
	return &UserInfoResponse{}
}

func (p *UserInfoResponse) InitDefault() {
}

var UserInfoResponse_Base_DEFAULT *base.BaseResp

func (p *UserInfoResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UserInfoResponse_Base_DEFAULT
	}
	return p.Base
}

var UserInfoResponse_Data_DEFAULT *base.User

func (p *UserInfoResponse) GetData() (v *base.User) {
	if !p.IsSetData() {
		return UserInfoResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *UserInfoResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *UserInfoResponse) SetData(val *base.User) {
	p.Data = val
}

func (p *UserInfoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *UserInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoResponse(%+v)", *p)
}

var fieldIDToName_UserInfoResponse = map[int16]string{
	1: "base",
	2: "data",
}

type UploadAvatarRequest struct {
	Data     []byte `thrift:"data,1" frugal:"1,default,binary" json:"data"`
	UserId   int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	FileName string `thrift:"file_name,3" frugal:"3,default,string" json:"file_name"`
}

func NewUploadAvatarRequest() *UploadAvatarRequest {
	return &UploadAvatarRequest{}
}

func (p *UploadAvatarRequest) InitDefault() {
}

func (p *UploadAvatarRequest) GetData() (v []byte) {
	return p.Data
}

func (p *UploadAvatarRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UploadAvatarRequest) GetFileName() (v string) {
	return p.FileName
}
func (p *UploadAvatarRequest) SetData(val []byte) {
	p.Data = val
}
func (p *UploadAvatarRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UploadAvatarRequest) SetFileName(val string) {
	p.FileName = val
}

func (p *UploadAvatarRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarRequest(%+v)", *p)
}

var fieldIDToName_UploadAvatarRequest = map[int16]string{
	1: "data",
	2: "user_id",
	3: "file_name",
}

type UploadAvatarResponse struct {
	Base *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	Data *base.User     `thrift:"data,2,optional" frugal:"2,optional,base.User" json:"data,omitempty"`
}

func NewUploadAvatarResponse() *UploadAvatarResponse {
	return &UploadAvatarResponse{}
}

func (p *UploadAvatarResponse) InitDefault() {
}

var UploadAvatarResponse_Base_DEFAULT *base.BaseResp

func (p *UploadAvatarResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UploadAvatarResponse_Base_DEFAULT
	}
	return p.Base
}

var UploadAvatarResponse_Data_DEFAULT *base.User

func (p *UploadAvatarResponse) GetData() (v *base.User) {
	if !p.IsSetData() {
		return UploadAvatarResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *UploadAvatarResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *UploadAvatarResponse) SetData(val *base.User) {
	p.Data = val
}

func (p *UploadAvatarResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UploadAvatarResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *UploadAvatarResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarResponse(%+v)", *p)
}

var fieldIDToName_UploadAvatarResponse = map[int16]string{
	1: "base",
	2: "data",
}

type GetMFAQrcodeRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetMFAQrcodeRequest() *GetMFAQrcodeRequest {
	return &GetMFAQrcodeRequest{}
}

func (p *GetMFAQrcodeRequest) InitDefault() {
}

func (p *GetMFAQrcodeRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetMFAQrcodeRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetMFAQrcodeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMFAQrcodeRequest(%+v)", *p)
}

var fieldIDToName_GetMFAQrcodeRequest = map[int16]string{
	1: "user_id",
}

type GetMFAQrcodeResponse struct {
	Base *base.BaseResp  `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	Data *base.MFAQrcode `thrift:"data,2,optional" frugal:"2,optional,base.MFAQrcode" json:"data,omitempty"`
}

func NewGetMFAQrcodeResponse() *GetMFAQrcodeResponse {
	return &GetMFAQrcodeResponse{}
}

func (p *GetMFAQrcodeResponse) InitDefault() {
}

var GetMFAQrcodeResponse_Base_DEFAULT *base.BaseResp

func (p *GetMFAQrcodeResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return GetMFAQrcodeResponse_Base_DEFAULT
	}
	return p.Base
}

var GetMFAQrcodeResponse_Data_DEFAULT *base.MFAQrcode

func (p *GetMFAQrcodeResponse) GetData() (v *base.MFAQrcode) {
	if !p.IsSetData() {
		return GetMFAQrcodeResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *GetMFAQrcodeResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *GetMFAQrcodeResponse) SetData(val *base.MFAQrcode) {
	p.Data = val
}

func (p *GetMFAQrcodeResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetMFAQrcodeResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetMFAQrcodeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMFAQrcodeResponse(%+v)", *p)
}

var fieldIDToName_GetMFAQrcodeResponse = map[int16]string{
	1: "base",
	2: "data",
}

type MFABindRequest struct {
	Code   string `thrift:"code,1" frugal:"1,default,string" json:"code"`
	Secret string `thrift:"secret,2" frugal:"2,default,string" json:"secret"`
	UserId int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
}

func NewMFABindRequest() *MFABindRequest {
	return &MFABindRequest{}
}

func (p *MFABindRequest) InitDefault() {
}

func (p *MFABindRequest) GetCode() (v string) {
	return p.Code
}

func (p *MFABindRequest) GetSecret() (v string) {
	return p.Secret
}

func (p *MFABindRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *MFABindRequest) SetCode(val string) {
	p.Code = val
}
func (p *MFABindRequest) SetSecret(val string) {
	p.Secret = val
}
func (p *MFABindRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *MFABindRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MFABindRequest(%+v)", *p)
}

var fieldIDToName_MFABindRequest = map[int16]string{
	1: "code",
	2: "secret",
	3: "user_id",
}

type MFABindResponse struct {
	Base *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
}

func NewMFABindResponse() *MFABindResponse {
	return &MFABindResponse{}
}

func (p *MFABindResponse) InitDefault() {
}

var MFABindResponse_Base_DEFAULT *base.BaseResp

func (p *MFABindResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return MFABindResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *MFABindResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}

func (p *MFABindResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *MFABindResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MFABindResponse(%+v)", *p)
}

var fieldIDToName_MFABindResponse = map[int16]string{
	1: "base",
}

type SearchUserIdsByNameRequest struct {
	Pattern  string `thrift:"pattern,1" frugal:"1,default,string" json:"pattern"`
	PageNum  int64  `thrift:"page_num,2" frugal:"2,default,i64" json:"page_num"`
	PageSize int64  `thrift:"page_size,3" frugal:"3,default,i64" json:"page_size"`
}

func NewSearchUserIdsByNameRequest() *SearchUserIdsByNameRequest {
	return &SearchUserIdsByNameRequest{}
}

func (p *SearchUserIdsByNameRequest) InitDefault() {
}

func (p *SearchUserIdsByNameRequest) GetPattern() (v string) {
	return p.Pattern
}

func (p *SearchUserIdsByNameRequest) GetPageNum() (v int64) {
	return p.PageNum
}

func (p *SearchUserIdsByNameRequest) GetPageSize() (v int64) {
	return p.PageSize
}
func (p *SearchUserIdsByNameRequest) SetPattern(val string) {
	p.Pattern = val
}
func (p *SearchUserIdsByNameRequest) SetPageNum(val int64) {
	p.PageNum = val
}
func (p *SearchUserIdsByNameRequest) SetPageSize(val int64) {
	p.PageSize = val
}

func (p *SearchUserIdsByNameRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchUserIdsByNameRequest(%+v)", *p)
}

var fieldIDToName_SearchUserIdsByNameRequest = map[int16]string{
	1: "pattern",
	2: "page_num",
	3: "page_size",
}

type SearchUserIdsByNameResponse struct {
	Base    *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	UserIds []int64        `thrift:"user_ids,2,optional" frugal:"2,optional,list<i64>" json:"user_ids,omitempty"`
}

func NewSearchUserIdsByNameResponse() *SearchUserIdsByNameResponse {
	return &SearchUserIdsByNameResponse{}
}

func (p *SearchUserIdsByNameResponse) InitDefault() {
}

var SearchUserIdsByNameResponse_Base_DEFAULT *base.BaseResp

func (p *SearchUserIdsByNameResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return SearchUserIdsByNameResponse_Base_DEFAULT
	}
	return p.Base
}

var SearchUserIdsByNameResponse_UserIds_DEFAULT []int64

func (p *SearchUserIdsByNameResponse) GetUserIds() (v []int64) {
	if !p.IsSetUserIds() {
		return SearchUserIdsByNameResponse_UserIds_DEFAULT
	}
	return p.UserIds
}
func (p *SearchUserIdsByNameResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *SearchUserIdsByNameResponse) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *SearchUserIdsByNameResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *SearchUserIdsByNameResponse) IsSetUserIds() bool {
	return p.UserIds != nil
}

func (p *SearchUserIdsByNameResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchUserIdsByNameResponse(%+v)", *p)
}

var fieldIDToName_SearchUserIdsByNameResponse = map[int16]string{
	1: "base",
	2: "user_ids",
}

type QueryUserByIDRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewQueryUserByIDRequest() *QueryUserByIDRequest {
	return &QueryUserByIDRequest{}
}

func (p *QueryUserByIDRequest) InitDefault() {
}

func (p *QueryUserByIDRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *QueryUserByIDRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *QueryUserByIDRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUserByIDRequest(%+v)", *p)
}

var fieldIDToName_QueryUserByIDRequest = map[int16]string{
	1: "user_id",
}

type QueryUserByIDResponse struct {
	Base *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	User *base.User     `thrift:"user,2,optional" frugal:"2,optional,base.User" json:"user,omitempty"`
}

func NewQueryUserByIDResponse() *QueryUserByIDResponse {
	return &QueryUserByIDResponse{}
}

func (p *QueryUserByIDResponse) InitDefault() {
}

var QueryUserByIDResponse_Base_DEFAULT *base.BaseResp

func (p *QueryUserByIDResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return QueryUserByIDResponse_Base_DEFAULT
	}
	return p.Base
}

var QueryUserByIDResponse_User_DEFAULT *base.User

func (p *QueryUserByIDResponse) GetUser() (v *base.User) {
	if !p.IsSetUser() {
		return QueryUserByIDResponse_User_DEFAULT
	}
	return p.User
}
func (p *QueryUserByIDResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *QueryUserByIDResponse) SetUser(val *base.User) {
	p.User = val
}

func (p *QueryUserByIDResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *QueryUserByIDResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *QueryUserByIDResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUserByIDResponse(%+v)", *p)
}

var fieldIDToName_QueryUserByIDResponse = map[int16]string{
	1: "base",
	2: "user",
}

type QueryUsersByIDsRequest struct {
	UserIds []int64 `thrift:"user_ids,1" frugal:"1,default,list<i64>" json:"user_ids"`
}

func NewQueryUsersByIDsRequest() *QueryUsersByIDsRequest {
	return &QueryUsersByIDsRequest{}
}

func (p *QueryUsersByIDsRequest) InitDefault() {
}

func (p *QueryUsersByIDsRequest) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *QueryUsersByIDsRequest) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *QueryUsersByIDsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUsersByIDsRequest(%+v)", *p)
}

var fieldIDToName_QueryUsersByIDsRequest = map[int16]string{
	1: "user_ids",
}

type QueryUsersByIDsResponse struct {
	Base  *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	Users []*base.User   `thrift:"users,2,optional" frugal:"2,optional,list<base.User>" json:"users,omitempty"`
}

func NewQueryUsersByIDsResponse() *QueryUsersByIDsResponse {
	return &QueryUsersByIDsResponse{}
}

func (p *QueryUsersByIDsResponse) InitDefault() {
}

var QueryUsersByIDsResponse_Base_DEFAULT *base.BaseResp

func (p *QueryUsersByIDsResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return QueryUsersByIDsResponse_Base_DEFAULT
	}
	return p.Base
}

var QueryUsersByIDsResponse_Users_DEFAULT []*base.User

func (p *QueryUsersByIDsResponse) GetUsers() (v []*base.User) {
	if !p.IsSetUsers() {
		return QueryUsersByIDsResponse_Users_DEFAULT
	}
	return p.Users
}
func (p *QueryUsersByIDsResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *QueryUsersByIDsResponse) SetUsers(val []*base.User) {
	p.Users = val
}

func (p *QueryUsersByIDsResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *QueryUsersByIDsResponse) IsSetUsers() bool {
	return p.Users != nil
}

func (p *QueryUsersByIDsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUsersByIDsResponse(%+v)", *p)
}

var fieldIDToName_QueryUsersByIDsResponse = map[int16]string{
	1: "base",
	2: "users",
}

type GetLastLogoutTimeRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetLastLogoutTimeRequest() *GetLastLogoutTimeRequest {
	return &GetLastLogoutTimeRequest{}
}

func (p *GetLastLogoutTimeRequest) InitDefault() {
}

func (p *GetLastLogoutTimeRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetLastLogoutTimeRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetLastLogoutTimeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLastLogoutTimeRequest(%+v)", *p)
}

var fieldIDToName_GetLastLogoutTimeRequest = map[int16]string{
	1: "user_id",
}

type GetLastLogoutTimeResponse struct {
	Base       *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
	LogoutTime *int64         `thrift:"logout_time,2,optional" frugal:"2,optional,i64" json:"logout_time,omitempty"`
}

func NewGetLastLogoutTimeResponse() *GetLastLogoutTimeResponse {
	return &GetLastLogoutTimeResponse{}
}

func (p *GetLastLogoutTimeResponse) InitDefault() {
}

var GetLastLogoutTimeResponse_Base_DEFAULT *base.BaseResp

func (p *GetLastLogoutTimeResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return GetLastLogoutTimeResponse_Base_DEFAULT
	}
	return p.Base
}

var GetLastLogoutTimeResponse_LogoutTime_DEFAULT int64

func (p *GetLastLogoutTimeResponse) GetLogoutTime() (v int64) {
	if !p.IsSetLogoutTime() {
		return GetLastLogoutTimeResponse_LogoutTime_DEFAULT
	}
	return *p.LogoutTime
}
func (p *GetLastLogoutTimeResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *GetLastLogoutTimeResponse) SetLogoutTime(val *int64) {
	p.LogoutTime = val
}

func (p *GetLastLogoutTimeResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetLastLogoutTimeResponse) IsSetLogoutTime() bool {
	return p.LogoutTime != nil
}

func (p *GetLastLogoutTimeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLastLogoutTimeResponse(%+v)", *p)
}

var fieldIDToName_GetLastLogoutTimeResponse = map[int16]string{
	1: "base",
	2: "logout_time",
}

type UpdateLastLogoutTimeRequest struct {
	UserId     int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	LogoutTime int64 `thrift:"logout_time,2" frugal:"2,default,i64" json:"logout_time"`
}

func NewUpdateLastLogoutTimeRequest() *UpdateLastLogoutTimeRequest {
	return &UpdateLastLogoutTimeRequest{}
}

func (p *UpdateLastLogoutTimeRequest) InitDefault() {
}

func (p *UpdateLastLogoutTimeRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateLastLogoutTimeRequest) GetLogoutTime() (v int64) {
	return p.LogoutTime
}
func (p *UpdateLastLogoutTimeRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateLastLogoutTimeRequest) SetLogoutTime(val int64) {
	p.LogoutTime = val
}

func (p *UpdateLastLogoutTimeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateLastLogoutTimeRequest(%+v)", *p)
}

var fieldIDToName_UpdateLastLogoutTimeRequest = map[int16]string{
	1: "user_id",
	2: "logout_time",
}

type UpdateLastLogoutTimeResponse struct {
	Base *base.BaseResp `thrift:"base,1" frugal:"1,default,base.BaseResp" json:"base"`
}

func NewUpdateLastLogoutTimeResponse() *UpdateLastLogoutTimeResponse {
	return &UpdateLastLogoutTimeResponse{}
}

func (p *UpdateLastLogoutTimeResponse) InitDefault() {
}

var UpdateLastLogoutTimeResponse_Base_DEFAULT *base.BaseResp

func (p *UpdateLastLogoutTimeResponse) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UpdateLastLogoutTimeResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateLastLogoutTimeResponse) SetBase(val *base.BaseResp) {
	p.Base = val
}

func (p *UpdateLastLogoutTimeResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateLastLogoutTimeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateLastLogoutTimeResponse(%+v)", *p)
}

var fieldIDToName_UpdateLastLogoutTimeResponse = map[int16]string{
	1: "base",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	GetUserInfo(ctx context.Context, req *UserInfoRequest) (r *UserInfoResponse, err error)

	UploadAvatar(ctx context.Context, req *UploadAvatarRequest) (r *UploadAvatarResponse, err error)

	GetMFAQrcode(ctx context.Context, req *GetMFAQrcodeRequest) (r *GetMFAQrcodeResponse, err error)

	MFABind(ctx context.Context, req *MFABindRequest) (r *MFABindResponse, err error)

	SearchUserIdsByName(ctx context.Context, req *SearchUserIdsByNameRequest) (r *SearchUserIdsByNameResponse, err error)

	QueryUserByID(ctx context.Context, req *QueryUserByIDRequest) (r *QueryUserByIDResponse, err error)

	QueryUsersByIDs(ctx context.Context, req *QueryUsersByIDsRequest) (r *QueryUsersByIDsResponse, err error)

	GetLastLogoutTime(ctx context.Context, req *GetLastLogoutTimeRequest) (r *GetLastLogoutTimeResponse, err error)

	UpdateLastLogoutTime(ctx context.Context, req *UpdateLastLogoutTimeRequest) (r *UpdateLastLogoutTimeResponse, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserInfoArgs struct {
	Req *UserInfoRequest `thrift:"req,1" frugal:"1,default,UserInfoRequest" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *UserInfoRequest

func (p *UserServiceGetUserInfoArgs) GetReq() (v *UserInfoRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *UserInfoRequest) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *UserInfoResponse `thrift:"success,0,optional" frugal:"0,optional,UserInfoResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *UserInfoResponse

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *UserInfoResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserInfoResponse)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceUploadAvatarArgs struct {
	Req *UploadAvatarRequest `thrift:"req,1" frugal:"1,default,UploadAvatarRequest" json:"req"`
}

func NewUserServiceUploadAvatarArgs() *UserServiceUploadAvatarArgs {
	return &UserServiceUploadAvatarArgs{}
}

func (p *UserServiceUploadAvatarArgs) InitDefault() {
}

var UserServiceUploadAvatarArgs_Req_DEFAULT *UploadAvatarRequest

func (p *UserServiceUploadAvatarArgs) GetReq() (v *UploadAvatarRequest) {
	if !p.IsSetReq() {
		return UserServiceUploadAvatarArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUploadAvatarArgs) SetReq(val *UploadAvatarRequest) {
	p.Req = val
}

func (p *UserServiceUploadAvatarArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUploadAvatarArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadAvatarArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUploadAvatarArgs = map[int16]string{
	1: "req",
}

type UserServiceUploadAvatarResult struct {
	Success *UploadAvatarResponse `thrift:"success,0,optional" frugal:"0,optional,UploadAvatarResponse" json:"success,omitempty"`
}

func NewUserServiceUploadAvatarResult() *UserServiceUploadAvatarResult {
	return &UserServiceUploadAvatarResult{}
}

func (p *UserServiceUploadAvatarResult) InitDefault() {
}

var UserServiceUploadAvatarResult_Success_DEFAULT *UploadAvatarResponse

func (p *UserServiceUploadAvatarResult) GetSuccess() (v *UploadAvatarResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUploadAvatarResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUploadAvatarResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadAvatarResponse)
}

func (p *UserServiceUploadAvatarResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUploadAvatarResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadAvatarResult(%+v)", *p)
}

var fieldIDToName_UserServiceUploadAvatarResult = map[int16]string{
	0: "success",
}

type UserServiceGetMFAQrcodeArgs struct {
	Req *GetMFAQrcodeRequest `thrift:"req,1" frugal:"1,default,GetMFAQrcodeRequest" json:"req"`
}

func NewUserServiceGetMFAQrcodeArgs() *UserServiceGetMFAQrcodeArgs {
	return &UserServiceGetMFAQrcodeArgs{}
}

func (p *UserServiceGetMFAQrcodeArgs) InitDefault() {
}

var UserServiceGetMFAQrcodeArgs_Req_DEFAULT *GetMFAQrcodeRequest

func (p *UserServiceGetMFAQrcodeArgs) GetReq() (v *GetMFAQrcodeRequest) {
	if !p.IsSetReq() {
		return UserServiceGetMFAQrcodeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetMFAQrcodeArgs) SetReq(val *GetMFAQrcodeRequest) {
	p.Req = val
}

func (p *UserServiceGetMFAQrcodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetMFAQrcodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetMFAQrcodeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetMFAQrcodeArgs = map[int16]string{
	1: "req",
}

type UserServiceGetMFAQrcodeResult struct {
	Success *GetMFAQrcodeResponse `thrift:"success,0,optional" frugal:"0,optional,GetMFAQrcodeResponse" json:"success,omitempty"`
}

func NewUserServiceGetMFAQrcodeResult() *UserServiceGetMFAQrcodeResult {
	return &UserServiceGetMFAQrcodeResult{}
}

func (p *UserServiceGetMFAQrcodeResult) InitDefault() {
}

var UserServiceGetMFAQrcodeResult_Success_DEFAULT *GetMFAQrcodeResponse

func (p *UserServiceGetMFAQrcodeResult) GetSuccess() (v *GetMFAQrcodeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetMFAQrcodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetMFAQrcodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMFAQrcodeResponse)
}

func (p *UserServiceGetMFAQrcodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetMFAQrcodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetMFAQrcodeResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetMFAQrcodeResult = map[int16]string{
	0: "success",
}

type UserServiceMFABindArgs struct {
	Req *MFABindRequest `thrift:"req,1" frugal:"1,default,MFABindRequest" json:"req"`
}

func NewUserServiceMFABindArgs() *UserServiceMFABindArgs {
	return &UserServiceMFABindArgs{}
}

func (p *UserServiceMFABindArgs) InitDefault() {
}

var UserServiceMFABindArgs_Req_DEFAULT *MFABindRequest

func (p *UserServiceMFABindArgs) GetReq() (v *MFABindRequest) {
	if !p.IsSetReq() {
		return UserServiceMFABindArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceMFABindArgs) SetReq(val *MFABindRequest) {
	p.Req = val
}

func (p *UserServiceMFABindArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceMFABindArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceMFABindArgs(%+v)", *p)
}

var fieldIDToName_UserServiceMFABindArgs = map[int16]string{
	1: "req",
}

type UserServiceMFABindResult struct {
	Success *MFABindResponse `thrift:"success,0,optional" frugal:"0,optional,MFABindResponse" json:"success,omitempty"`
}

func NewUserServiceMFABindResult() *UserServiceMFABindResult {
	return &UserServiceMFABindResult{}
}

func (p *UserServiceMFABindResult) InitDefault() {
}

var UserServiceMFABindResult_Success_DEFAULT *MFABindResponse

func (p *UserServiceMFABindResult) GetSuccess() (v *MFABindResponse) {
	if !p.IsSetSuccess() {
		return UserServiceMFABindResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceMFABindResult) SetSuccess(x interface{}) {
	p.Success = x.(*MFABindResponse)
}

func (p *UserServiceMFABindResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceMFABindResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceMFABindResult(%+v)", *p)
}

var fieldIDToName_UserServiceMFABindResult = map[int16]string{
	0: "success",
}

type UserServiceSearchUserIdsByNameArgs struct {
	Req *SearchUserIdsByNameRequest `thrift:"req,1" frugal:"1,default,SearchUserIdsByNameRequest" json:"req"`
}

func NewUserServiceSearchUserIdsByNameArgs() *UserServiceSearchUserIdsByNameArgs {
	return &UserServiceSearchUserIdsByNameArgs{}
}

func (p *UserServiceSearchUserIdsByNameArgs) InitDefault() {
}

var UserServiceSearchUserIdsByNameArgs_Req_DEFAULT *SearchUserIdsByNameRequest

func (p *UserServiceSearchUserIdsByNameArgs) GetReq() (v *SearchUserIdsByNameRequest) {
	if !p.IsSetReq() {
		return UserServiceSearchUserIdsByNameArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSearchUserIdsByNameArgs) SetReq(val *SearchUserIdsByNameRequest) {
	p.Req = val
}

func (p *UserServiceSearchUserIdsByNameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSearchUserIdsByNameArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSearchUserIdsByNameArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSearchUserIdsByNameArgs = map[int16]string{
	1: "req",
}

type UserServiceSearchUserIdsByNameResult struct {
	Success *SearchUserIdsByNameResponse `thrift:"success,0,optional" frugal:"0,optional,SearchUserIdsByNameResponse" json:"success,omitempty"`
}

func NewUserServiceSearchUserIdsByNameResult() *UserServiceSearchUserIdsByNameResult {
	return &UserServiceSearchUserIdsByNameResult{}
}

func (p *UserServiceSearchUserIdsByNameResult) InitDefault() {
}

var UserServiceSearchUserIdsByNameResult_Success_DEFAULT *SearchUserIdsByNameResponse

func (p *UserServiceSearchUserIdsByNameResult) GetSuccess() (v *SearchUserIdsByNameResponse) {
	if !p.IsSetSuccess() {
		return UserServiceSearchUserIdsByNameResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSearchUserIdsByNameResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchUserIdsByNameResponse)
}

func (p *UserServiceSearchUserIdsByNameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSearchUserIdsByNameResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSearchUserIdsByNameResult(%+v)", *p)
}

var fieldIDToName_UserServiceSearchUserIdsByNameResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUserByIDArgs struct {
	Req *QueryUserByIDRequest `thrift:"req,1" frugal:"1,default,QueryUserByIDRequest" json:"req"`
}

func NewUserServiceQueryUserByIDArgs() *UserServiceQueryUserByIDArgs {
	return &UserServiceQueryUserByIDArgs{}
}

func (p *UserServiceQueryUserByIDArgs) InitDefault() {
}

var UserServiceQueryUserByIDArgs_Req_DEFAULT *QueryUserByIDRequest

func (p *UserServiceQueryUserByIDArgs) GetReq() (v *QueryUserByIDRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUserByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUserByIDArgs) SetReq(val *QueryUserByIDRequest) {
	p.Req = val
}

func (p *UserServiceQueryUserByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUserByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserByIDArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserByIDArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUserByIDResult struct {
	Success *QueryUserByIDResponse `thrift:"success,0,optional" frugal:"0,optional,QueryUserByIDResponse" json:"success,omitempty"`
}

func NewUserServiceQueryUserByIDResult() *UserServiceQueryUserByIDResult {
	return &UserServiceQueryUserByIDResult{}
}

func (p *UserServiceQueryUserByIDResult) InitDefault() {
}

var UserServiceQueryUserByIDResult_Success_DEFAULT *QueryUserByIDResponse

func (p *UserServiceQueryUserByIDResult) GetSuccess() (v *QueryUserByIDResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUserByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUserByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryUserByIDResponse)
}

func (p *UserServiceQueryUserByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUserByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserByIDResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserByIDResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUsersByIDsArgs struct {
	Req *QueryUsersByIDsRequest `thrift:"req,1" frugal:"1,default,QueryUsersByIDsRequest" json:"req"`
}

func NewUserServiceQueryUsersByIDsArgs() *UserServiceQueryUsersByIDsArgs {
	return &UserServiceQueryUsersByIDsArgs{}
}

func (p *UserServiceQueryUsersByIDsArgs) InitDefault() {
}

var UserServiceQueryUsersByIDsArgs_Req_DEFAULT *QueryUsersByIDsRequest

func (p *UserServiceQueryUsersByIDsArgs) GetReq() (v *QueryUsersByIDsRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUsersByIDsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUsersByIDsArgs) SetReq(val *QueryUsersByIDsRequest) {
	p.Req = val
}

func (p *UserServiceQueryUsersByIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUsersByIDsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUsersByIDsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUsersByIDsArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUsersByIDsResult struct {
	Success *QueryUsersByIDsResponse `thrift:"success,0,optional" frugal:"0,optional,QueryUsersByIDsResponse" json:"success,omitempty"`
}

func NewUserServiceQueryUsersByIDsResult() *UserServiceQueryUsersByIDsResult {
	return &UserServiceQueryUsersByIDsResult{}
}

func (p *UserServiceQueryUsersByIDsResult) InitDefault() {
}

var UserServiceQueryUsersByIDsResult_Success_DEFAULT *QueryUsersByIDsResponse

func (p *UserServiceQueryUsersByIDsResult) GetSuccess() (v *QueryUsersByIDsResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUsersByIDsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUsersByIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryUsersByIDsResponse)
}

func (p *UserServiceQueryUsersByIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUsersByIDsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUsersByIDsResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUsersByIDsResult = map[int16]string{
	0: "success",
}

type UserServiceGetLastLogoutTimeArgs struct {
	Req *GetLastLogoutTimeRequest `thrift:"req,1" frugal:"1,default,GetLastLogoutTimeRequest" json:"req"`
}

func NewUserServiceGetLastLogoutTimeArgs() *UserServiceGetLastLogoutTimeArgs {
	return &UserServiceGetLastLogoutTimeArgs{}
}

func (p *UserServiceGetLastLogoutTimeArgs) InitDefault() {
}

var UserServiceGetLastLogoutTimeArgs_Req_DEFAULT *GetLastLogoutTimeRequest

func (p *UserServiceGetLastLogoutTimeArgs) GetReq() (v *GetLastLogoutTimeRequest) {
	if !p.IsSetReq() {
		return UserServiceGetLastLogoutTimeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetLastLogoutTimeArgs) SetReq(val *GetLastLogoutTimeRequest) {
	p.Req = val
}

func (p *UserServiceGetLastLogoutTimeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetLastLogoutTimeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetLastLogoutTimeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetLastLogoutTimeArgs = map[int16]string{
	1: "req",
}

type UserServiceGetLastLogoutTimeResult struct {
	Success *GetLastLogoutTimeResponse `thrift:"success,0,optional" frugal:"0,optional,GetLastLogoutTimeResponse" json:"success,omitempty"`
}

func NewUserServiceGetLastLogoutTimeResult() *UserServiceGetLastLogoutTimeResult {
	return &UserServiceGetLastLogoutTimeResult{}
}

func (p *UserServiceGetLastLogoutTimeResult) InitDefault() {
}

var UserServiceGetLastLogoutTimeResult_Success_DEFAULT *GetLastLogoutTimeResponse

func (p *UserServiceGetLastLogoutTimeResult) GetSuccess() (v *GetLastLogoutTimeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetLastLogoutTimeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetLastLogoutTimeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetLastLogoutTimeResponse)
}

func (p *UserServiceGetLastLogoutTimeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetLastLogoutTimeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetLastLogoutTimeResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetLastLogoutTimeResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateLastLogoutTimeArgs struct {
	Req *UpdateLastLogoutTimeRequest `thrift:"req,1" frugal:"1,default,UpdateLastLogoutTimeRequest" json:"req"`
}

func NewUserServiceUpdateLastLogoutTimeArgs() *UserServiceUpdateLastLogoutTimeArgs {
	return &UserServiceUpdateLastLogoutTimeArgs{}
}

func (p *UserServiceUpdateLastLogoutTimeArgs) InitDefault() {
}

var UserServiceUpdateLastLogoutTimeArgs_Req_DEFAULT *UpdateLastLogoutTimeRequest

func (p *UserServiceUpdateLastLogoutTimeArgs) GetReq() (v *UpdateLastLogoutTimeRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateLastLogoutTimeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateLastLogoutTimeArgs) SetReq(val *UpdateLastLogoutTimeRequest) {
	p.Req = val
}

func (p *UserServiceUpdateLastLogoutTimeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateLastLogoutTimeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateLastLogoutTimeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateLastLogoutTimeArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateLastLogoutTimeResult struct {
	Success *UpdateLastLogoutTimeResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateLastLogoutTimeResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateLastLogoutTimeResult() *UserServiceUpdateLastLogoutTimeResult {
	return &UserServiceUpdateLastLogoutTimeResult{}
}

func (p *UserServiceUpdateLastLogoutTimeResult) InitDefault() {
}

var UserServiceUpdateLastLogoutTimeResult_Success_DEFAULT *UpdateLastLogoutTimeResponse

func (p *UserServiceUpdateLastLogoutTimeResult) GetSuccess() (v *UpdateLastLogoutTimeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateLastLogoutTimeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateLastLogoutTimeResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateLastLogoutTimeResponse)
}

func (p *UserServiceUpdateLastLogoutTimeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateLastLogoutTimeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateLastLogoutTimeResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateLastLogoutTimeResult = map[int16]string{
	0: "success",
}
